### PR TITLE
feat(av): Add windows defender config options

### PR DESCRIPTION
**Pull request by ken9ross**
## Intent of Change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## Description

Add new config options to windows defender config
Add support for cfn-hup to allow updates to AWS::CloudFormation::Init
Refactor computetask_awswin_volumemount to work with cfn-hup

## Motivation and Context

Antivirus config from https://github.com/gs-gs/ha-ema-arcgis/issues/10 and bugs discovered during testing of same

## How Has This Been Tested?

Locally generated and deployed to AWS

### Prerequisite PRs:

- https://github.com/hamlet-io/engine/pull/1814

### Dependent PRs:

- None

### Consumer Actions:

- None

### CODE REVIEW

**Comment by ml019** [comment]
Looks ok to me but I think @roleyfoley should take a look as well.

@ken9ross Just wanted to confirm that while supporting antivirus, adding the task into the task lists in the master data still requires configuration before the function becomes active/controlled?

**Comment by ken9ross** [comment]
@ml019 Not sure I understand your question. 

The new computetask is "supported by" awslinux_ospatching and awswin_antivirus (and not awswin_ospatching) so that anything using the _awswin profile requires the computetask_awswin_antivirus, while anything using the linux profile does not require any change.

**Comment by ml019** [comment]
@ken9ross My query is for the situation where I want windows but not AV. IT looked to me like the assumption was that it was always needed.

**Comment by ken9ross** [comment]
@ml019 The Windows AMIs include Windows Defender, so it's always there, (but you can turn it off through the antivirus configuration options if you want to get rid of it)

**Review by ml019 — APPROVED** [review]

**Pull request merged**
